name: "Auto-label PRs for Auto-Merge"

on:
  pull_request_target:
    types: [opened, synchronize, ready_for_review]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  auto-label-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: "Add automerge label if safe"
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            // Example: Only label if not a draft and from 'main' branch
            if (!pr.draft && pr.base.ref === 'main') {
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['automerge'],
              });
            }
