name: "PR Automation"

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, ready_for_review]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: "Automatically label PRs"
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: "Auto-assign PRs"
        uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/auto_assign.yml

  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: "Enable Auto Merge for eligible PRs"
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          merge-method: squash
          labels: "automerge"
          requireReview: true
