name: Verify
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 9 }
      - name: Install
        run: pnpm install
      - name: Placeholder check
        run: node scripts/check-placeholders.mjs
      - name: Type check web
        run: pnpm --filter web build --if-present
